### ISSUE TITLE
No trigger for successful measurement

### ISSUE THREAD

**Issue by MrBlue90** [slasktrat/com.speedtest#1]
Hi there!

First thanks for developing this app!
I've been waiting for it quite some time :)

Though, I seem to encounter some issues with it.
I created 3 different flows in Homey:
1. This flow is started -> Run Speedtest
2. Speedtest completed -> Send a push notification
3. Speedtest failed -> Send a push notification

Once I Speedtest fails, I receive a push message.
However, when the Speedtest ran well, it doesn't seem to trigger the push message.

Do you have any idea what could be the issue?
Please let me know in case you would like me to test something.

Regards,
Rick

**Comment by xgbcman** [comment]
I have exactly the same problem!

**Comment by slasktrat** [comment]
Hi

Thanks for using the app, and for reporting this issue!

Very strange as this works perfectly in my end. But I will take a look and do some testing. Are you using any tags from the result in the push notification? And are your name listed multiple times when you select receiver for push notification?

**Comment by slasktrat** [comment]
Ah, sorry! It was actually no longer working. I used this a lot when developing the app, but haven't had the push notification enabled for some time. I have found the issue and are submitting fix as we speak. The update will need to be approved by Athom so it can take a few days until it is available for download. (or you can send me your email and I will add you to the alpha channel)

**Comment by MrBlue90** [comment]
Thanks slasktrat!
Looking forward to try the update.
For what it's worth, I was trying to use the following tags in this way:
`Speedtest performed! Ping: Ping latency | DL: Download speed (mbps) (Download speed difference from last result (percentage)) | UL: Upload speed (mbps) (Upload speed difference from last result (percentage))`

**Comment by slasktrat** [comment]
Thanks. I will let you know when it is published :)

BTW: I have noticed that long push messages are impossible to read (at least on my Huawei), because I'm only able to see the first two lines with no option to expand. But that is a different issue :) They still are received.

**Comment by MrBlue90** [comment]
Thanks for the heads up! The message with nulled (0) tags seemed to fit, so fingers crossed 😄

**Comment by slasktrat** [comment]
Hi

The updated version (0.0.2) is now published and available at https://apps.athom.com/app/com.speedtest

**Comment by MrBlue90** [comment]
I hereby confirm that the issue got fixed by the update.
+1 for the fast resolution!

**Comment by xgbcman** [comment]
Work as a charm!
Observation 1: As you predicted the measured value will not always be the correct for higher speeds. My 100/10 fiber connection is measured to about 20/10. It's good enough to assess if the connection is working or not.
Observation 2: To confirm a Test in flow with the "Speedtest Completed"-card you need to fill all five fields with values. Maybe you should consider to put in default values like zeroes?
Good work :)

**Comment by MrBlue90** [comment]
> Observation 1: As you predicted the measured value will not always be the correct for higher speeds. 
> My 100/10 fiber connection is measured to about 20/10. It's good enough to assess if the connection > is working or not.

Yup.. Same here (even lower). Any chance Homey will also not be fast enough to perform a proper speedtest?

> Observation 2: To confirm a Test in flow with the "Speedtest Completed"-card you need to fill all five 
> fields with values. Maybe you should consider to put in default values like zeroes?
> Good work :)

I created a separate flow (This flow is started -> Run Speedtest) for testing. This will give you actual values instead of nulled ones.

**Comment by xgbcman** [comment]
> I created a separate flow (This flow is started -> Run Speedtest) for testing. This will give you actual values instead of nulled ones.

In the desktop version for Homey you can confirm a "Test" of flows while you are creating them.
